# Generated by Django 3.2.5 on 2021-07-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0002_auto_20210710_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='web_site',
            field=models.URLField(null=True),
        ),
    ]
