# Generated by Django 3.2.5 on 2021-07-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0004_auto_20210710_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-track_listing']},
        ),
    ]
