# Generated by Django 3.2.4 on 2021-07-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0005_alter_song_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['track_listing']},
        ),
        migrations.RemoveField(
            model_name='album',
            name='image',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='song',
            name='audio_file',
        ),
    ]
