# Generated by Django 3.2.4 on 2021-07-14 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0006_auto_20210711_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='date',
        ),
    ]
